  <section class="container-fluid h-100 bg-success">
    <div  class="d-flex justify-content-end w-100 flex-wrap">
      <a href="/cadastre-se" id="cadastrar" class="btn btn-warning pl-4 pr-4 mt-3">Cadastrar</a>
    </div>
    <div class="d-flex justify-content-center align-content-center flex-wrap h-75">
      <form action="/login" method="post" class="w-25 bg-white rounded shadow pr-5 pl-5">
        <fieldset class="">
          <legend class="text-center pt-2">Entrar</legend>
          <div class="form-group">
            <small><?= isset($_SESSION["msgLogin"]) ? "<span class=\"text-danger\">" . $_SESSION["msgLogin"] . "<br></span>" : ""; ?></small>
            <label for="email">Email:</label>
            <input type="email" class="form-control" name="email" id="email" required aria-describedby="emailHelpId" placeholder="">
            <label for="senha" class="pt-1">Senha:</label>
            <input type="password" class="form-control" name="senha" id="senha" required placeholder="">
            <br>
            <div class="text-center">
              <input name="login" id="login" class="btn btn-success pl-5 pr-5" type="submit" value="Login">
            </div>
          </div>
        </fieldset>
      </form>
    </div>
  </section>

  <?php
  if (isset($_SESSION["msgLogin"])) {
    unset($_SESSION["msgLogin"]);
  }
  ?>