<!-- Page Container -->
<link rel="stylesheet" href="../../css/bootstrap.min.css">
<div class="w3-container w3-content" style="max-width:1400px;margin-top:80px">
  <!-- The Grid -->
  <div class="w3-row">

    <!-- Left Column -->
    <div class="w3-col m3">
      <!-- Profile -->


      <div class="w3-card w3-round w3-white">
        <div class="w3-container">
          <h4 class="w3-center">Bem-vindo</h4>
          <p class="w3-center"><i class="fa fa-user-circle-o text-primary" style="font-size: 5em; " aria-hidden="true"></i></p>
          <hr>
          <p><i class="fa fa-pencil fa-fw w3-margin-right w3-text-theme"></i>NOME</p>
        </div>
      </div>
      <br>

      <!-- End Left Column -->
    </div>

    <!-- Middle Column -->
    <div class="w3-col m7 pb-3">
      <div class="w3-row-padding">
        <div class="w3-card w3-round w3-white h-100">
          <form action="/home/tarefa/editar/confirmar?id=<?=$this->view->tarefa['id_tarefas'] ?>"; method="post" class="">
            <h2 class="pt-3 text-center">Cadastrar Tarefa</h2>
            <div class="w-100 pr-3 pl-3 ">
              <div class=" form-group d-flex">
                <label for="nome">Nome da tarefa:</label>
                <input type="text" class="form-control" name="nome" id="nome" required minlength="5" maxlength="150" placeholder="nome do evento" value="<?= $this->view->tarefa['nome'] ?>">
              </div>
              <div class="form-group">
                <label for="descricao">Descrição:</label> <br>
                <textarea class="form-control" style="resize: none;" required minlength="5" name="descricao" id="descricao" rows="5" maxlength="450"><?= $this->view->tarefa['descricao'] ?></textarea>
              </div>
              <div class="row">
                <div class="form-group col-6">
                  <label for="prioridade">Prioridade:</label> <br>
                  <select class="custom-select" required name="prioridade" id="prioridade">
                    <!-- <?php foreach ($this->view->prioridades as $prioridade) { ?> -->
                    <option value="<?= $prioridade['id_prioridades'] ?>" <?= $this->view->tarefa['id_prioridades'] == $prioridade['id_prioridades'] ? "selected" : "" ?>><?= $prioridade['nome'] ?></option>
                    <!-- <?php } ?> -->
                  </select>
                </div>
                <div class="form-group col-6">
                  <label for="datahora">Data:</label><br>
                  <?php
                  $date = new DateTime($this->view->tarefa['data_conclusao']);
                  $data1 =  $date->format('Y-m-d');
                  $data2 =  $date->format('H:i');
                  ?>
                  <input id="datahora" class="form-control" required min="<?= date("Y-m-d") . "T" . date("H:i"); ?>" type="datetime-local" name="datahora" value="<?= date($data1) . "T" . date($data2); ?>">
                </div>
              </div>
              <div class="w3-row d-flex">
                <button class="w3-button flex-fill w3-green w3-section" title="Editar Tarefa"><i class="fa fa-check" aria-hidden="true"></i></button>
              </div>
            </div>

          </form>

        </div>

      </div>

      <!-- End Middle Column -->
    </div>

    <!-- Right Column -->
    <div class="w3-col m2">

      <div class="w3-card w3-round w3-white w3-padding-16 w3-center">
        <p>ADS</p>
      </div>
      <br>

      <div class="w3-card w3-round w3-white w3-padding-16 w3-center">
        <p>ADS</p>
      </div>
      <br>


      <div class="w3-card w3-round w3-white w3-padding-16 w3-center">
        <p>ADS</p>
      </div>
      <br>

      <div class="w3-card w3-round w3-white w3-padding-32 w3-center">
        <p><i class="fa fa-bug w3-xxlarge"></i></p>
      </div>

      <!-- End Right Column -->
    </div>

    <!-- End Grid -->
  </div>

  <!-- End Page Container -->
</div>