<!DOCTYPE html>
<html class="h-100">

<head>
  <meta charset="utf-8" />
  <title><?= $this->view->titulo ?></title>

  <link rel="stylesheet" href="css/bootstrap.min.css">

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</head>

<body class="h-100">

  <nav class="navbar navbar-expand-sm navbar-light bg-warning">
    <a class="navbar-brand" href="#">AGENDA-PHP</a>
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <button class="nav-link btn-link btn" href="#">Tarefas Atrasadas</button>
      </li>
      <li class="nav-item">
        <button class="nav-link btn-link btn" href="#">Tarefas Concluídas</button>
      </li>
      <li class="nav-item">
        <div class="dropdown open">
          <button class="btn btn-link nav-link dropdown-toggle" type="button" id="triggerId" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Tarefas Pendentes
          </button>
          <div class="dropdown-menu" aria-labelledby="triggerId">
            <button class="dropdown-item" href="#">Todas as Tarefas</button>
            <button class="dropdown-item" href="#">Tarefas Importantes</button>
            <button class="dropdown-item" href="#">Tarefas menos importantes</button>
            <button class="dropdown-item" href="#">Tarefas de baixa importância</button>
          </div>
        </div>
      </li>
      <li class="nav-item">
        <button class="nav-link btn-link btn" href="#">Cadastrar Tarefas</button>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <button class="btn btn-danger my-2 my-sm-0 pr-5 pl-5" onclick="header('location: /sair');" type="submit">Sair</button>
    </form>
  </nav>


  <?= $this->content() ?>
</body>

</html>