-- MySQL Script generated by MySQL Workbench
-- Thu Dec  3 20:10:57 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema agenda
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `agenda` ;

-- -----------------------------------------------------
-- Schema agenda
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `agenda` DEFAULT CHARACTER SET utf8 ;
USE `agenda` ;

-- -----------------------------------------------------
-- Table `agenda`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agenda`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `agenda`.`usuarios` (
  `id_usuarios` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `apelido` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `nome` VARCHAR(300) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuarios`),
  UNIQUE INDEX `id_usuarios_UNIQUE` (`id_usuarios` ASC) VISIBLE,
  UNIQUE INDEX `apelido_UNIQUE` (`apelido` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agenda`.`prioridades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agenda`.`prioridades` ;

CREATE TABLE IF NOT EXISTS `agenda`.`prioridades` (
  `id_prioridades` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(450) NULL,
  PRIMARY KEY (`id_prioridades`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agenda`.`tarefas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agenda`.`tarefas` ;

CREATE TABLE IF NOT EXISTS `agenda`.`tarefas` (
  `id_tarefas` INT NOT NULL,
  `descrição` VARCHAR(450) NOT NULL,
  `nome` VARCHAR(150) NOT NULL,
  `data_conclusao` TIMESTAMP NOT NULL,
  `id_usuarios` INT UNSIGNED NOT NULL,
  `id_prioridades` INT NOT NULL,
  PRIMARY KEY (`id_tarefas`),
  INDEX `fk_tarefa_usuarios1_idx` (`id_usuarios` ASC) VISIBLE,
  INDEX `fk_tarefa_prioridades1_idx` (`id_prioridades` ASC) VISIBLE,
  CONSTRAINT `fk_tarefa_usuarios1`
    FOREIGN KEY (`id_usuarios`)
    REFERENCES `agenda`.`usuarios` (`id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tarefa_prioridades1`
    FOREIGN KEY (`id_prioridades`)
    REFERENCES `agenda`.`prioridades` (`id_prioridades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
